nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/': ~

# parameters:
#     oauth_access_token_lifetime: 3600
#     oauth_refresh_token_lifetime: 1209600
#     cors_oauth_allow_origin:
#         - '*'
#     cors_oauth_allow_headers:
#         - '*'
#     cors_oauth_max_age: 3600
#     cors_api_allow_origin:
#         - '*'
#     cors_api_allow_headers:
#         - '*'
#     cors_api_max_age: 
#     cors_hosts:
#         - ^api\.
#         - ^odr-crm-api\.
#     app_url: 'https://crm.onedayroofing.com'
#     api_url: 'https://crm-api.onedayroofing.com'
    

# nelmio_cors:
#     defaults:
#         allow_credentials: false
#         allow_origin: []
#         allow_headers: []
#         allow_methods: []
#         expose_headers: []
#         # max_age: 31104000
#         max_age: 0
#         hosts: []
#         origin_regex: false
#         forced_allow_origin_value: ~
#     paths:
#         '^/oauth/':
#             #allow_origin: '%cors_oauth_allow_origin%'
#             #allow_headers: '%cors_oauth_allow_headers%'
#             allow_origin: '*'
#             allow_headers: '*'
#             allow_methods: ['GET', 'POST']
#             max_age: 0
#         '^/api/':
#             allow_origin: '%cors_api_allow_origin%'
#             allow_headers: '%cors_api_allow_headers%'
#             allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#             max_age: 31104000
#         '^/socket/':
#             allow_credentials: true
#             allow_origin: '%cors_api_allow_origin%'
#             allow_headers: '%cors_api_allow_headers%'
#             allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#             hosts: '%cors_hosts%'
#             max_age: 31104000