fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"      
    prefix: /admin

# FOSOAuthServerBundle

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"