client:
    path:     /
    defaults: { _controller: App\Lev\CRMBundle\Controller\Oauth2\ClientController::indexAction }
    
client_new:
    path:     /new
    defaults: { _controller: App\Lev\CRMBundle\Controller\Oauth2\ClientController::newAction }

client_create:
    path:     /create
    defaults: { _controller: App\Lev\CRMBundle\Controller\Oauth2\ClientController::createAction }
    methods:  POST

client_edit:
    path:     /{id}/edit
    defaults: { _controller: App\Lev\CRMBundle\Controller\Oauth2\ClientController::editAction }

client_update:
    path:     /{id}/update
    defaults: { _controller: App\Lev\CRMBundle\Controller\Oauth2\ClientController::updateAction }
    methods:  [POST, PUT]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: App\Lev\CRMBundle\Controller\Oauth2\ClientController::deleteAction }
    methods:  [POST, DELETE]
