security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        admin:
            pattern:    ^/admin
            security:   true
            anonymous: true
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                csrf_parameter:     false
                default_target_path: lev_api_admin
            logout:
                path:   fos_user_security_logout
                target: lev_api_admin

        oauth_authorize:
            pattern:   ^/oauth/v2/auth
            form_login:
                provider:  fos_userbundle
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            anonymous: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

        twilio:
            pattern:    ^/twilio
            security:   false

        twiliovoice:
            pattern:    ^/api/v1/twilio/voice/
            security:   false
            
    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
        # - { path: ^/socket/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/socket/auth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/socket/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/, role: IS_AUTHENTICATED_FULLY }
