parameters:
    lev_api.user_manager.class                   : App\Lev\APIBundle\Model\UserManager
    lev_api.user.util.user_manipulator.class     : App\Lev\APIBundle\Util\UserManipulator
    lev_api.api_key.provider.user_provider.class : App\Lev\APIBundle\Security\Authentication\Provider\UserProvider
    lev_api.security.role_hierarchy.class        : App\Lev\APIBundle\Security\Core\Role\RoleHierarchy
    lev_api.user.role.getter.class               : App\Lev\APIBundle\Util\UserRoleGetter

    lev_api.crud_roles:
        staff           : [ view, create, update, delete ]
        staffrole       : [ view, create, update, delete ]
        office          : [ view, create, update, delete ]
        advisoryzipcode : [ view, create, update, delete ]
        product         : [ view, create, update, delete ]
        productextra    : [ view, create, update, delete ]
        customer        : [ view, create, update, delete ]
        appointment     : [ view, create, update, delete ]
        sale            : [ view, create, update, delete ]
        project         : [ view, create, update, delete ]
        contractor      : [ view, create, update, delete ]
        institution     : [ view, create, update, delete ]
        call            : [ view, create, update, delete ]
        callrecord      : [ view, create, update, delete ]
    lev_api.other_roles:
        ROLE_REPORT: Report Access

services:
    lev_api.user_manager:
        class:     "%lev_api.user_manager.class%"
        arguments: ["@fos_user.util.password_updater", "@fos_user.util.canonical_fields_updater", "@doctrine", "%fos_user.model.user.class%"]

    lev_api.user.util.user_manipulator:
        class:     "%lev_api.user.util.user_manipulator.class%"
        arguments: ["@lev_api.user_manager"]
        public: true
        
    lev_api.api_key.provider.user_provider:
        class: "%lev_api.api_key.provider.user_provider.class%"
        arguments: ["@fos_user.user_provider"]

    security.role_hierarchy:
       class: "%lev_api.security.role_hierarchy.class%"
       arguments: ["%security.role_hierarchy.roles%", "%lev_api.crud_roles%", "%lev_api.other_roles%"]

    lev_api.user.role.getter:
        public: true
        class: "%lev_api.user.role.getter.class%"
        arguments: ["@security.role_hierarchy"]